# Generated by Django 6.0.7 on 2026-09-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuser',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('INSTRUCTOR', 'Instructor'), ('PARENT', 'Parent'), ('ADMIN', 'Admin'), ('SCHOOL_PARTNER', 'School Partner')], default='STUDENT', max_length=25),
        ),
        migrations.AlterField(
            model_name='tuser',
            name='email',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
