# Generated by Django 6.0.7 on 2026-09-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tuser_role_alter_tuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuser',
            name='phone',
            field=models.CharField(blank=True, help_text='optional phone you can also use to login', max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tuser',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=15),
        ),
        migrations.AlterField(
            model_name='tuser',
            name='email',
            field=models.EmailField(help_text='required email', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='tuser',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('INSTRUCTOR', 'Instructor'), ('PARENT', 'Parent'), ('ADMIN', 'Admin'), ('SCHOOL_PARTNER', 'School Partner')], default='STUDENT', help_text='primary role', max_length=25),
        ),
    ]
