# Generated by Django 6.0.7 on 2026-09-26 19:23

import apps.accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tuser_phone_tuser_status_alter_tuser_email_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tuser',
            managers=[
                ('objects', apps.accounts.managers.TUserManager()),
            ],
        ),
    ]
