# Generated by Django 6.0.7 on 2026-09-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_tuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuser',
            name='school_name',
            field=models.CharField(blank=True, help_text='School partners only: the school this account represents.', max_length=150),
        ),
    ]
