# Generated by Django 6.0.7 on 2026-10-01 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tuser_school_name'),
        ('people', '0002_lesson_school_track_cohort_lesson_track_enrollment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuser',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='people.school'),
        ),
    ]
