# Generated by Django 6.0.7 on 2026-10-01 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('position', models.PositiveIntegerField(help_text='Order within the track. 1, 2, 3...')),
                ('content', models.TextField(blank=True, help_text='Lesson text/instructions.')),
                ('video_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['track', 'position'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('referral_code', models.CharField(blank=True, max_length=12, unique=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('kind', models.CharField(choices=[('TRACK', 'Long Track'), ('SHORT_COURSE', 'Short Course')], default='TRACK', max_length=20)),
                ('age_range', models.CharField(blank=True, help_text='e.g. "4–7"', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('price_naira', models.PositiveIntegerField(help_text='Whole naira, no kobo.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from enrollment without deleting.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['price_naira'],
            },
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Web Dev Batch B – November"', max_length=100)),
                ('enrollment_opens_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment_closes_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_lesson', models.ForeignKey(blank=True, help_text='Shared progress pointer for every student in this batch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='people.lesson')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='people.track')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='people.track'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_mode', models.CharField(choices=[('COHORT', 'Cohort'), ('ONE_ON_ONE', 'One-on-one'), ('SELF_PACED', 'Self-paced')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending payment'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING_PAYMENT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='people.cohort')),
                ('enrolled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='people.student')),
                ('current_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='people.lesson')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='people.school')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='people.track')),
            ],
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('track', 'position'), name='unique_position_per_track'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING_PAYMENT', 'ACTIVE'])), fields=('student', 'track'), name='one_live_enrollment_per_student_track'),
        ),
    ]
