# Generated by Django 6.0.7 on 2026-10-01 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_lesson_school_track_cohort_lesson_track_enrollment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TRSDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('default_weight', models.DecimalField(decimal_places=2, help_text='Percent, e.g. 20.00', max_digits=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('assessment_type', models.CharField(choices=[('QUIZ', 'Quiz'), ('EXERCISE', 'Exercise'), ('PROJECT_SUBMISSION', 'Project submission'), ('INSTRUCTOR_RATING', 'Instructor rating')], max_length=20)),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('requires_manual_review', models.BooleanField(default=False)),
                ('media_required', models.BooleanField(default=False, help_text='Submission must include a photo/video/link.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(blank=True, help_text='Leave blank for a track-level capstone assessment.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='people.lesson')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='people.track')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='people.trsdimension')),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('AUTO_PASSED', 'Auto-passed'), ('NEEDS_REVIEW', 'Needs review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected — resubmit')], default='SUBMITTED', max_length=20)),
                ('media', models.FileField(blank=True, null=True, upload_to='submissions/%Y/%m/')),
                ('notes', models.TextField(blank=True, help_text="Student's own notes, or reviewer feedback.")),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='people.assessment')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='people.enrollment')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TRSScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='people.trsdimension')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trs_scores', to='people.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'dimension'), name='one_score_per_dimension')],
            },
        ),
    ]
