# Generated by Django 6.0.7 on 2026-10-03 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_trsdimension_assessment_attempt_trsscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trsdimension',
            name='default_weight',
        ),
    ]
