# Generated by Django 6.0.7 on 2026-10-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_remove_trsdimension_default_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='guardian_invite_code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
