# Generated by Django 6.0.7 on 2026-10-08 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_student_guardian_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='meeting_url',
            field=models.URLField(blank=True, help_text='Live session link. Shown only to active enrollments.'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='schedule_note',
            field=models.CharField(blank=True, help_text='e.g. "Saturdays 10:00–11:30 WAT"', max_length=200),
        ),
        migrations.AddField(
            model_name='cohort',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Leave blank for a public cohort anyone can join. Set it to make the cohort private to that school.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cohorts', to='people.school'),
        ),
        migrations.AddField(
            model_name='track',
            name='audience',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('SCHOOL', 'School programme')], default='PUBLIC', help_text='School programmes are only visible to schools that have a cohort on them.', max_length=10),
        ),
        migrations.AddField(
            model_name='track',
            name='offers_cohort',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='track',
            name='offers_one_on_one',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='track',
            name='offers_self_paced',
            field=models.BooleanField(default=True),
        ),
    ]
